<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>SourceUtils.WebExport</RootNamespace>
    <AssemblyName>SourceUtils.WebExport</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="JetBrains.Annotations" Version="2025.2.4" />
    <PackageReference Include="Magick.NET-Q8-AnyCPU" Version="14.16.0" />
    <PackageReference Include="MediaTypeMap" Version="2.1.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="OpenTK" Version="2.0.0" />
    <PackageReference Include="Ziks.WebServer" Version="0.1.6317.26952-alpha" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SourceUtils\SourceUtils.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\tsconfig.json" />
    <Content Include="Resources\index.template.html" />
    <Content Include="Resources\js\facepunch.webgame.js" />
    <Content Include="Resources\js\sourceutils.js" />
    <Content Include="Resources\styles\mapviewer.css" />
  </ItemGroup>

</Project>
