<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>SourceUtils</RootNamespace>
    <AssemblyName>SourceUtils</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SharpZipLib" Version="1.4.2" />
    <PackageReference Include="LZMA-SDK" Version="22.1.1" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="KeyValues.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SourceUtils.Parsing\SourceUtils.Parsing.csproj" />
  </ItemGroup>

</Project>
