<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>SourceUtils.MapExport.Console</RootNamespace>
    <AssemblyName>SourceUtils.MapExport</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SourceUtils.MapExport.Core\SourceUtils.MapExport.Core.csproj" />
  </ItemGroup>

</Project>
