name: .NET - Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'
    - name: Restore dependencies
      run: dotnet restore SourceUtils.sln
    - name: Build
      run: dotnet build SourceUtils.sln --configuration Debug --no-restore
    - name: Test
      run: dotnet test SourceUtils.Test/SourceUtils.Test.csproj --configuration Debug --no-build --logger trx --results-directory ./test-results
